### ISSUE TITLE
File with Space character is returning the MediaInfo object as null

### ISSUE THREAD

**Issue by YogiFoxCloud** [caprica/vlcj-info#10]
We get the presigned url of the file from AWS S3 and passing the path to MediaInfo.mediaInfo(path) returns the null object.
When run in command gives the proper result.

**Comment by caprica** [comment]
Can you try and URLEncode the path.

**Comment by YogiFoxCloud** [comment]
It is an encoded path. ( with %20 for spaces ). Also it works well with command mediainfo 'presignedUrl' and able to download locally from the presigned url.

**Comment by YogiFoxCloud** [comment]
Closing the ticket. It was double encoded.
