### ISSUE TITLE
NullPointerException in MediaInfo

### ISSUE THREAD

**Issue by anshul90** [caprica/vlcj-info#5]
Hi, I'm following the steps as you mentioned to get the info a video but I'm getting NPE in the below mentioned line.

`MediaInfo info = MediaInfo.mediaInfo("/Users/anshul.c.tyagiVideos/123.mp4");`

Please let me know if you can help me. Thanks

**Comment by caprica** [comment]
Is this related to your comment in #3?

Did you resolve the problem you described in #3?
