### ISSUE TITLE
Use of MediaInfoFile changes behavior of MediaInfo?

### ISSUE THREAD

**Issue by robgilde** [caprica/vlcj-info#7]
My application uses MediaInfo at times to get full info about a file.  My application also uses MediaInfoFile at other times to get just the duration.  After a usage of MediaInfoFile, subsequent usages of MediaInfo return only the duration, instead of the full info.
```
        MediaInfoFile mif = new MediaInfoFile(f);
        if (mif.open()) {
            String durationString = mif.info("Video;%Duration/String3%");
            mif.close();
        }

        MediaInfo video = MediaInfo.mediaInfo(f);
        video.dump(new StringWriter());
```

Am I using this correctly?  Is this the intended behavior or an inherent limitation?

Other than this issue, the package has been a wonderful addition to my application.  Thanks very much!

**Comment by caprica** [comment]
Glad you find this useful, thanks.

This is a strange problem. I will try and find some time to do some debugging.

**Comment by caprica** [comment]
Just to be completely clear, you're saying in the code you posted above, if you remove the MediaInfoFile part, then the MediaInfo part below produces different results?

**Comment by caprica** [comment]
Nevermind I can reproduce this exactly.

MediaInfoFile:
```
    public String info(String value) {
        LibMediaInfo.INSTANCE.MediaInfo_Option(null, new WString("Inform"), new WString(value)); <-----
        WString result = LibMediaInfo.INSTANCE.MediaInfo_Inform(handle);
        return result != null ? result.toString() : null;
    }
```

Setting the format option here, as indicated above, sets it for EVERY operation globally. It is NOT scoped per-handle.

Note that the handle parameter on the indicated line is null. However, setting the handle correctly makes no difference:

MediaInfoFile:
```
    public String info(String value) {
        LibMediaInfo.INSTANCE.MediaInfo_Option(handle, new WString("Inform"), new WString(value)); <-----
        WString result = LibMediaInfo.INSTANCE.MediaInfo_Inform(handle);
        return result != null ? result.toString() : null;
    }
```

Later in MediaInfo:
```
    int opened = lib.MediaInfo_Open(handle, new WString(filename));
    if (opened == 1) {
        WString data = lib.MediaInfo_Inform(handle);     <--- here we call the API method without setting any formatting options, no MediaInfo_option() call
        lib.MediaInfo_Close(handle);
        result = new Parser(data.toString()).parse();
    }
```

The indicated line here shows that we invoke the native API method without setting any format options. 

So this looks very strange to me, but apparently that is how the native MediaInfo API works - those options get set globally. This can be "fixed" by setting the empty string for options in MediaInfo:

```
    int opened = lib.MediaInfo_Open(handle, new WString(filename));
    if (opened == 1) {
        lib.MediaInfo_Option(handle, new WString("Inform"), new WString(""));    <------ "fix"
        WString data = lib.MediaInfo_Inform(handle);
        lib.MediaInfo_Close(handle);
        result = new Parser(data.toString()).parse();
    }
```

I would have thought the format options should be scoped to the handle, but apparently no.

**Comment by caprica** [comment]
I will find some time to make a change and do a new release.

**Comment by caprica** [comment]
OK, please try version 2.0.1 when it arrives in Maven Central, it can take a few hours.

Thanks for the initial report.

**Comment by robgilde** [comment]
Thanks, Caprica!  I have verified that 2.0.1 works as expected in my application.
