### ISSUE TITLE
StackOverflowError via Duration.hours

### ISSUE THREAD

**Issue by jbye** [caprica/vlcj-info#8]
Hello,

Thank you for making this library available.

There seems to be a StackOverflow issue with the hours getter in the Duration class. Looks like it's a typo?

https://github.com/caprica/vlcj-info/blob/master/src/main/java/uk/co/caprica/vlcjinfo/Duration.java#L81

**Comment by caprica** [comment]
Thanks for the report.

Indeed that looks like a lazy typo. I'll push a fix soon.

**Comment by caprica** [comment]
Fixed at 8ce5d9a93149c62d799571d5f1ddff00f1302870.

New release pending.

**Comment by caprica** [comment]
New release 2.0.2 on its way to Maven Central repo.
